export enum AuditAction {
  CREATE = 'create',
  READ = 'read',
  UPDATE = 'update',
  DELETE = 'delete',
  LOGIN = 'login',
  LOGOUT = 'logout',
  VIEW = 'view',
  APPROVE = 'approve',
  REJECT = 'reject',
  ENABLE = 'enable',
  DISABLE = 'disable',
  SUSPEND = 'suspend',
  UNSUSPEND = 'unsuspend',
  ACTIVATE = 'activate',
  DEACTIVATE = 'deactivate',
  GRANT = 'grant',
  REVOKE = 'revoke',
  PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST',
  PASSWORD_RESET_VERIFY = 'PASSWORD_RESET_VERIFY',
  PASSWORD_RESET = 'PASSWORD_RESET',
  ADD = 'add',
  REMOVE = 'remove',
  ASSIGN_ROLE = 'assign_role',
  REVOKE_ROLE = 'revoke_role',
  ASSIGN_PERMISSION = 'assign_permission',
  REVOKE_PERMISSION = 'revoke_permission',
  ACTION = 'action', // Generic action for custom events
}

export enum AuditModule {
  AUTH = 'auth',
  USER = 'user',
  ADMIN = 'admin',
  AUDIT = 'audit',
  SYSTEM = 'system',
  SECURITY = 'security',
}
